#!/usr/bin/env zsh

install_stow() {
    echo "Stow is not installed. Attempting to install..."

    if command -v apt >/dev/null 2>&1; then
        sudo apt update && sudo apt install -y stow
    elif command -v brew >/dev/null 2>&1; then
        brew install stow
    elif command -v pacman >/dev/null 2>&1; then
        sudo pacman -Sy --noconfirm stow
    elif command -v dnf >/dev/null 2>&1; then
        sudo dnf install -y stow
    elif command -v yum >/dev/null 2>&1; then
        sudo yum install -y stow
    else
        echo "No supported package manager found. Please install 'stow' manually."
        return 1
    fi
}

if ! command -v stow >/dev/null 2>&1; then
    install_stow
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${(%):-%N}")" && pwd)"

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd "$DOTFILES" || exit

echo "Initializing git submodules..."
git submodule update --init --recursive

echo "Stowing..."
pushd $SCRIPT_DIR/stows
stow -v -t $HOME --adopt */

git restore .

popd
