#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

grep=""
dry_run=false

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run=true
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run = true ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $env -- grep: $grep"

runs_dir=`find $SCRIPT_DIR/runs -mindepth 1 -maxdepth 1`

run_script() {
    script_dir=$1

    script_cmd=$(basename $script_dir)

    main_script=$script_dir/main_script
    if [[ -d $script_dir/dependencies ]]; then
        deps=`find $script_dir/dependencies -mindepth 1 -maxdepth 1 -executable`
        for d in $deps; do
            log "Installing dependency $(basename $d) for $(basename $script_dir)"
            if [[ $dry_run == false ]]; then
                source "$d"
            fi
        done
    fi

    if command -v $script_cmd >/dev/null 2>&1; then
        log "$script_cmd is already installed"
    else
        log "Installing $script_cmd"
        if [[ $dry_run == false ]]; then
            source "$main_script"
        fi
    fi



    if [[ -d $script_dir/addons ]]; then
        addons=`find $script_dir/addons -mindepth 1 -maxdepth 1 -executable`
        for d in $addons; do
            log "Installing addon $(basename $d) for $script_cmd"
            if [[ $dry_run == false ]]; then
                source "$d"
            fi
        done
    fi
}

for s in $runs_dir; do
    if basename $s | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi

    log "running script: $s"

    run_script $s
done
