#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

grep=""
dry_run=false

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run=true
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run = true ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $env -- grep: $grep"

runs_dir=`find $SCRIPT_DIR/runs -mindepth 1 -maxdepth 1 -executable`

for s in $runs_dir; do
    if basename $s | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi

    log "running script: $s"

    if [[ $dry_run == false ]]; then
        $s
    fi
done
