#!/usr/bin/env bash

read -p "Install Golang 1.24.4? (y/n) " ACCEPT
ACCEPT=${ACCEPT:-y}

if [[ "$ACCEPT" =~ ^[Yy]$ ]]; then
    echo "Installing Golang 1.24.4..."
    curl -LO https://go.dev/dl/go1.24.4.linux-amd64.tar.gz
    sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.24.4.linux-amd64.tar.gz
    rm go1.24.4.linux-amd64.tar.gz
else
    echo "Golang installation skipped."
fi
