#!/usr/bin/env bash

# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# in lieu of restarting the shell
[ -z "${XDG_CONFIG_HOME-}" ] && NVM_DIR="${HOME}/.nvm" || NVM_DIR="${XDG_CONFIG_HOME}/nvm"

source "$NVM_DIR/nvm.sh"

# Download and install Node.js:
nvm install 22

# Verify the Node.js version:
node -v # Should print "v22.17.0".
nvm current # Should print "v22.17.0".

# Verify npm version:
npm -v # Should print "10.9.2".
